[en]
  title = "leoay tech blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ko"


[cn]
  title = "leoay技术日志"
  languageName = "中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/cn"
